pip install pandas -y;
pip install statsmodels -y;
pip install scikit-learn -y;
pip install numpy -y;
pip install sqlalchemy -y;
pip install psutil -y;
pip install matplotlib -y;
pip install yellowbrick -y;
pip install joblib -y;
pip install scipy -y;
pip install psycopg2 -y;
pip install openpyxl -y;
pip install tabulate -y;
pip install dtreeviz -y;
pip install yellowbrick;